#!/bin/sh
./vuln.sh trace '${upper:itworks}'
./vuln.sh debug '${upper:itworks}'
./vuln.sh info '${upper:itworks}'
./vuln.sh warn '${upper:itworks}'
./vuln.sh error '${upper:itworks}'
./vuln.sh fatal '${upper:itworks}'
./vuln.sh printf '${upper:itworks}'
./215vuln.sh trace '${upper:itworks}'
./215vuln.sh debug '${upper:itworks}'
./215vuln.sh info '${upper:itworks}'
./215vuln.sh warn '${upper:itworks}'
./215vuln.sh error '${upper:itworks}'
./215vuln.sh fatal '${upper:itworks}'
./215vuln.sh printf '${upper:itworks}'
